### ISSUE TITLE
[bug] Change language

### ISSUE THREAD

**Issue by Romz24** [openmultiplayer/homepage#21]
The language change is not displayed correctly on my computer. I checked in two browsers **Chrome** and **Opera**.

![ScreenShot00071](https://user-images.githubusercontent.com/2458113/56241895-b4268280-609f-11e9-81e8-aec4953d05e4.jpg)

**Comment by Southclaws** [comment]
Yeah I'm aware of this, turns out I wasn't aware of the lack of support for unicode flag symbols across systems! This is what it _should_ look like:

![image](https://user-images.githubusercontent.com/1636971/56273857-8704bf00-60f5-11e9-804f-8afe7f118a59.png)

I plan to replace this with SVG symbols or a custom font so it displays correctly on older systems.

**Comment by Southclaws** [comment]
This might be a good solution: https://github.com/lipis/flag-icon-css if anyone wants to try and implement this, wait for #27 to be merged first because Y_Less has updated the language menu.

**Comment by Y-Less** [comment]
#38
